import { workflowTemplate } from "./workflow.template.js";

interface ReadmeTemplateOptions {
  androidProjectPath: string;
  runnerLabel: string;
  androidApplicationId: string;
  keystorePath: string;
  enablePlayDeploy: boolean;
  enableSentry: boolean;
}

export function renderGitHubWorkflow(options: Parameters<typeof workflowTemplate>[0]): string {
  return workflowTemplate(options);
}

export function renderReadme(options: ReadmeTemplateOptions): string {
  return `# Android CI

Generated by \`android-ci init\`.

## Project Contract

- Android project path: \`${options.androidProjectPath}\`
- Runner label: \`${options.runnerLabel}\`
- Android application id: \`${options.androidApplicationId}\`
- Runner keystore path: \`${options.keystorePath}\`
- Play deploy enabled: \`${String(options.enablePlayDeploy)}\`
- Sentry enabled: \`${String(options.enableSentry)}\`

## Shared VM Assumption

This repo assumes you already have one shared Android build VM with:

- Android SDK installed at \`/opt/android-sdk\`
- a GitHub self-hosted runner registered with label \`${options.runnerLabel}\`
- release keystore present on the VM at \`${options.keystorePath}\`
${options.enablePlayDeploy ? "- Play service account JSON present on the VM at \\`/home/Sahilhasnain/android-secrets/play-store-key.json\\`\n" : ""}${options.enableSentry ? "- optional Sentry token provided as a GitHub secret\n" : ""}

## GitHub Secrets

Required:

- \`ANDROID_KEYSTORE_PASSWORD\`
- \`ANDROID_KEY_ALIAS\`
- \`ANDROID_KEY_PASSWORD\`
${options.enableSentry ? "- \\`SENTRY_AUTH_TOKEN\\`\n" : ""} 

## GitHub Variables

Optional overrides:

- \`ANDROID_APPLICATION_ID\`
- \`ANDROID_KEYSTORE_PATH\`
${options.enablePlayDeploy ? "- \\`PLAY_STORE_JSON_KEY_PATH\\`\n" : ""}${options.enableSentry ? "- \\`SENTRY_ORG\\`\n- \\`SENTRY_PROJECT\\`\n" : ""}

## Next Steps

1. Confirm the shared VM already has the expected key files.
2. Add the repo secrets above.
3. If your keystore \`.jks\` is in this repo root, copy it to the VM:

\`\`\`powershell
ssh -i .\\ssh_key Sahilhasnain@98.70.32.91 "mkdir -p /home/Sahilhasnain/android-secrets && chmod 700 /home/Sahilhasnain/android-secrets"
scp -i .\\ssh_key ".\\your-release-key.jks" Sahilhasnain@98.70.32.91:/home/Sahilhasnain/android-secrets/release.keystore
\`\`\`

4. Review \`.github/workflows/android-self-hosted.yml\`.
5. Trigger a preview build first, then production.
`;
}
