import { workflowTemplate } from "./workflow.template.js";

interface ReadmeTemplateOptions {
  androidProjectPath: string;
  runnerLabel: string;
  androidApplicationId: string;
  keystorePath: string;
  enablePlayDeploy: boolean;
  enableSentry: boolean;
}

export function renderGitHubWorkflow(options: Parameters<typeof workflowTemplate>[0]): string {
  return workflowTemplate(options);
}

export function renderReadme(options: ReadmeTemplateOptions): string {
  return `# Android CI

Generated by \`android-ci init\`.

## Detected Android Project

\`${options.androidProjectPath}\`

## Generated Defaults

- Runner label: \`${options.runnerLabel}\`
- Android application id: \`${options.androidApplicationId}\`
- Runner keystore path: \`${options.keystorePath}\`
- Play deploy enabled: \`${String(options.enablePlayDeploy)}\`
- Sentry enabled: \`${String(options.enableSentry)}\`

## Next Steps

1. Configure a self-hosted GitHub runner.
2. Add repo secrets for signing and store upload.
3. Set repo variables like \`ANDROID_APPLICATION_ID\`, \`ANDROID_KEYSTORE_PATH\`, and optional Sentry values.
`;
}
