interface FastfileTemplateOptions {
  androidApplicationId: string;
  enableSentry: boolean;
}

export function fastfileTemplate(options: FastfileTemplateOptions): string {
  const sentryCheck = options.enableSentry
    ? `  private_lane :ensure_sentry_token do
    if ENV["SENTRY_AUTH_TOKEN"].to_s.empty?
      UI.important("SENTRY_AUTH_TOKEN not set, Sentry upload will be skipped")
    end
  end

`
    : "";

  const sentryCall = options.enableSentry ? "    ensure_sentry_token\n" : "";

  return `# This file contains the fastlane.tools configuration
# Generated by android-ci init

default_platform(:android)

platform :android do
  private_lane :ensure_play_store_key do
    json_key_path = ENV["SUPPLY_JSON_KEY"] || "/tmp/play-store-key.json"
    unless File.exist?(json_key_path)
      UI.user_error!("Play Store JSON key not found at: #{json_key_path}")
    end
  end

${sentryCheck}  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
${sentryCall}    ensure_play_store_key

    # Check if we should skip the build (when AAB is already built by Gradle)
    skip_build = ENV["SKIP_ANDROID_BUILD"] == "true"
    
    unless skip_build
      # Build the bundle if not skipped
      gradle(task: "clean bundleRelease")
    end
    
    upload_to_play_store(
      track: options[:track] || ENV["PLAY_TRACK"] || "internal",
      aab: options[:aab] || "app/build/outputs/bundle/release/app-release.aab",
      package_name: ENV["ANDROID_APPLICATION_ID"] || "${options.androidApplicationId}",
      json_key: ENV["SUPPLY_JSON_KEY"] || "/tmp/play-store-key.json",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
`;
}
